/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author pagua
 */
public class VistaNuevoCliente extends javax.swing.JPanel {

    /**
     * Creates new form VistaNuevoCliente
     */
    public VistaNuevoCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNuevoCliente = new javax.swing.JLabel();
        jLabelNombreTitular = new javax.swing.JLabel();
        nombreTitular = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dniTitular = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonoTitular = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreConyuge = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dniConyuge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        telefonoConyuge = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        labelNuevoCliente.setText("DATOS DEL TITULAR");

        jLabelNombreTitular.setText("Nombre Completo");

        nombreTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTitularActionPerformed(evt);
            }
        });

        jLabel2.setText("DNI");

        jLabel3.setText("Telefono");

        telefonoTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoTitularActionPerformed(evt);
            }
        });

        jLabel4.setText("CONYUGE");

        jLabel5.setText("Nombre Completo");

        nombreConyuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreConyugeActionPerformed(evt);
            }
        });

        jLabel6.setText("DNI");

        jLabel7.setText("Telefono");

        jLabel8.setText("Fecha de Nacimiento");

        jLabel9.setText("Fecha de Nacimiento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNuevoCliente)
                    .addComponent(jLabelNombreTitular)
                    .addComponent(nombreTitular)
                    .addComponent(jLabel2)
                    .addComponent(dniTitular)
                    .addComponent(jLabel3)
                    .addComponent(telefonoTitular)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(nombreConyuge)
                    .addComponent(jLabel6)
                    .addComponent(dniConyuge)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(telefonoConyuge, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(jLabel9))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNuevoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNombreTitular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dniConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telefonoConyuge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nombreConyugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreConyugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreConyugeActionPerformed

    private void telefonoTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoTitularActionPerformed
       // TODO add your handling code here:
    }//GEN-LAST:event_telefonoTitularActionPerformed

    private void nombreTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTitularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTitularActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dniConyuge;
    private javax.swing.JTextField dniTitular;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNombreTitular;
    private javax.swing.JLabel labelNuevoCliente;
    private javax.swing.JTextField nombreConyuge;
    private javax.swing.JTextField nombreTitular;
    private javax.swing.JTextField telefonoConyuge;
    private javax.swing.JTextField telefonoTitular;
    // End of variables declaration//GEN-END:variables
}
