package Modelo;
// Generated 13/02/2018 00:50:03 by Hibernate Tools 4.3.1



/**
 * Cliente generated by hbm2java
 */
public class Cliente extends Persona  implements java.io.Serializable {


     private Integer idCliente;
     private Persona persona;
     private Persona conyuge;

    public Cliente() {
        this.persona = (Persona)this;
    }

    public Cliente(Persona persona) {
        this.persona = (Persona)this;
       this.setPersona(persona);
    }
    
    public Cliente(Persona p_persona, Persona conyuge) {
       super(p_persona);
       this.persona = (Persona)this;
       this.setConyuge(conyuge);
    }
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    private void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public Persona getPersona() {
        return this;
    }
    
    private void setPersona(Persona persona) {
        this.persona = persona;
    }

    public Persona getConyuge() {
        return conyuge;
    }

    private void setConyuge(Persona conyuge) {
        this.conyuge = conyuge;
    }




}


