package Modelo;
// Generated 13/02/2018 00:50:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Direccion generated by hbm2java
 */
public class Direccion  implements java.io.Serializable {


     private Integer idDireccion;
     private Persona persona;
     private String pais;
     private String provincia;
     private String localidad;
     private String direccionExacta;
     private Set personas = new HashSet(0);

    public Direccion() {
    }

	
    public Direccion(String pais, String provincia, String localidad, String direccionExacta) {
        this.pais = pais;
        this.provincia = provincia;
        this.localidad = localidad;
        this.direccionExacta = direccionExacta;
    }
    public Direccion(Persona persona, String pais, String provincia, String localidad, String direccionExacta, Set personas) {
       this.persona = persona;
       this.pais = pais;
       this.provincia = provincia;
       this.localidad = localidad;
       this.direccionExacta = direccionExacta;
       this.personas = personas;
    }
   
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getDireccionExacta() {
        return this.direccionExacta;
    }
    
    public void setDireccionExacta(String direccionExacta) {
        this.direccionExacta = direccionExacta;
    }
    public Set getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set personas) {
        this.personas = personas;
    }




}


