package Modelo;
// Generated 13/02/2018 00:50:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private int dni;
     private Direccion direccion;
     private String nombre;
     private Date fechaNacimiento;
     private String cuil;
     private Set clientes = new HashSet(0);
     private Set direcciones = new HashSet(0);

    public Persona() {
    }

	
    public Persona(int dni) {
        this.dni = dni;
    }
    public Persona(int dni, Direccion direccion, String nombre, Date fechaNacimiento, String cuil, Set clientes, Set direccions) {
       this.dni = dni;
       this.direccion = direccion;
       this.nombre = nombre;
       this.fechaNacimiento = fechaNacimiento;
       this.cuil = cuil;
       this.clientes = clientes;
       this.direcciones = direccions;
    }
    public Persona(Persona p) {
       this.dni = p.getDni();
       this.direccion = p.getDireccion();
       this.nombre = p.getNombre();
       this.fechaNacimiento = p.getFechaNacimiento();
       this.cuil = p.getCuil();
       this.clientes = p.getClientes();
       this.direcciones = p.getDireccions();
    }
   
    public int getDni() {
        return this.dni;
    }
    
    public void setDni(int dni) {
        this.dni = dni;
    }
    public Direccion getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(Direccion direccion) {
        this.direccion = direccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getCuil() {
        return this.cuil;
    }
    
    public void setCuil(String cuil) {
        this.cuil = cuil;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getDireccions() {
        return this.direcciones;
    }
    
    public void setDireccions(Set direccions) {
        this.direcciones = direccions;
    }




}


